### ISSUE TITLE
The spread `...options` is not commonJs and this causing build issues in some builders.

### ISSUE THREAD

**Issue by dennisat** [shinnn/read-json-sync#3]
This is introduced in 2.0.1.

https://github.com/shinnn/read-json-sync/commit/432270116f5c328df52059d2cea1aa47fea2b6d9#diff-168726dbe96b3ce427e7fedce31bb0bcR32

**Comment by shinnn** [comment]
You're wrong.

**Comment by dennisat** [comment]
I didn't say that is not valid ECMAScript syntax! I said that is not valid commonJS!
**Be polite.**

**Comment by shinnn** [comment]
Both wrong.
